#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "chuwiki"
name = "ChuWiki"
description.en = "Simple, fast and flexible wiki"
description.fr = "Wiki simple, rapide et flexible"

version = "2.0~ynh2"

maintainers = ["Stylix58"]

[upstream]
license = "AGPL-3.0-only"
website = "http://chuwiki.genezys.net/"
demo = "http://chuwiki.genezys.net/wiki/Bac%20%C3%A0%20sable"
admindoc = "http://chuwiki.genezys.net/"
code = "https://github.com/genezys/chuwiki"

[integration]
yunohost = ">= 11.0.9"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "150M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/chuwiki"

    [install.title]
    ask.en = "Choose a title for the wiki you want to create"
    ask.fr = "Choisissez un titre pour le wiki que vous souhaitez créer"
    type = "string"
    example = "ChuWiki"
    default = "ChuWiki"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["en", "es", "fr", "zh"]
    default = "en"

    [install.init_main_permission]
    help.en = "If yes, this app will can be accessible by everyone."
    help.fr = "Si oui, cette app pourra être accessible par tout le monde."
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "http://chuwiki.genezys.net/download/chuwiki-2.0.zip"
    sha256 = "d944241e87469417a55f91cb513628859f33364fe5a6e6d97ce933c4efcf8329"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "php7.4",
        "php7.4-fpm",
    ]
